"""Wear Quake's own art on PANTHEON geometry — correctly, and at the best
resolution we have.

Two facts settle the design.

**Reuse the IMAGE, not the world shader.** The first door proof borrowed
`textures/gothic_block/blocks15` by name and rendered translucent, because
that name resolves to a WORLD shader whose first stage is `map $lightmap` and
a model carries no lightmap coordinates. The texture image was never the
problem. So a PANTHEON material has a PANTHEON name, its own model-appropriate
stages, and points at whatever image we want to wear -- including every one of
Quake Live's own.

**We already have those images at 4x.** `creative_suite/comfy/photoreal/
pipelines/upscale_only/pak00/` holds 5,646 pak00 textures upscaled to
1024x1024 by 4x-UltraSharp (Phase 5, PH5-1). This module prefers them and
falls back to the original in `pak00.pk3`, recording per material which one it
used -- a render that says "photoreal" has to be able to prove it.

    from engine.pantheon.material_adapter import Material, build

    build([Material("pantheon/door_body", "textures/gothic_block/blocks15_blue"),
           Material("pantheon/glyph", "textures/base_light/proto_lightblue",
                    kind="EMISSIVE")],
          out_dir=Path(".tmp/pk3"))

Nothing here modifies a Steam pak (ENG-4); images are copied out read-only and
shipped in our own `zzz_*.pk3` (ENG-2).
"""
from __future__ import annotations

import hashlib
import json
import os
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

PAK = Path("C:/Program Files (x86)/Steam/steamapps/common/Quake Live/baseq3/pak00.pk3")

# The Phase 5 upscale corpus is ~30 GB of generated images and lives once on
# disk, outside any worktree. Its location is explicit rather than guessed,
# and whichever file is used is recorded with its hash in the manifest, so a
# frame that claims "photoreal" can be checked.
_PHOTOREAL_REL = Path("creative_suite/comfy/photoreal/pipelines/upscale_only/pak00")


def photoreal_root() -> Path:
    """$PANTHEON_PHOTOREAL_ROOT, else this checkout, else the project store."""
    env = os.environ.get("PANTHEON_PHOTOREAL_ROOT")
    if env:
        return Path(env)
    here = Path(__file__).resolve().parents[2] / _PHOTOREAL_REL
    if here.exists():
        return here
    return Path("G:/QUAKE_LEGACY") / _PHOTOREAL_REL


PHOTOREAL = photoreal_root()

SURFACE = "SURFACE"        # ordinary lit geometry
EMISSIVE = "EMISSIVE"      # a light source: unlit core plus a restrained halo


@dataclass
class Material:
    """A PANTHEON material name, and the Quake image it wears."""

    name: str                       # e.g. "pantheon/door_body"
    source: str                     # e.g. "textures/gothic_block/blocks15_blue"
    kind: str = SURFACE
    halo: float = 0.10              # EMISSIVE only: additive amplitude
    resolved: dict = field(default_factory=dict)

    @property
    def shader_name(self) -> str:
        return f"textures/{self.name}"


def _photoreal(source: str, root: Path) -> Path | None:
    """The 4x upscale of a pak00 texture, if Phase 5 produced one."""
    p = root / f"{source}.png"
    return p if p.exists() else None


def _from_pak(source: str, pak: Path) -> tuple[str, bytes] | None:
    """The original image out of pak00 -- read-only, never modified."""
    if not pak.exists():
        return None
    with zipfile.ZipFile(pak) as z:
        names = set(z.namelist())
        for ext in (".tga", ".jpg", ".png"):
            if source + ext in names:
                return ext, z.read(source + ext)
    return None


def resolve(m: Material, *, pak: Path = PAK, photoreal_root: Path = PHOTOREAL) -> Material:
    """Pick the best available image and record WHICH, with a hash."""
    hi = _photoreal(m.source, photoreal_root)
    if hi is not None:
        data = hi.read_bytes()
        m.resolved = {"origin": "PHOTOREAL_UPSCALE_4X", "path": str(hi),
                      "ext": ".png", "bytes": len(data),
                      "sha256": hashlib.sha256(data).hexdigest()[:16]}
        return m
    got = _from_pak(m.source, pak)
    if got is None:
        raise FileNotFoundError(f"{m.source}: not in the photoreal set and not in {pak}")
    ext, data = got
    m.resolved = {"origin": "PAK00_ORIGINAL", "path": f"{pak.name}:{m.source}{ext}",
                  "ext": ext, "bytes": len(data),
                  "sha256": hashlib.sha256(data).hexdigest()[:16]}
    return m


def shader_text(materials: Sequence[Material]) -> str:
    """Model shaders. Not one stage samples $lightmap.

    `nopicmip` matters here: r_picmip exists to make textures cheaper, and a
    1024x1024 upscale that the renderer then halves twice is an upscale we
    paid for and threw away.
    """
    out = ["// PANTHEON materials -- generated by engine/pantheon/material_adapter.py",
           "// Quake's own images, worn by MODELS: plain map stages with",
           "// rgbGen lightingDiffuse, exactly like every weapon in the game.",
           ""]
    for m in materials:
        img = f"textures/{m.name}{m.resolved.get('ext', '.tga')}"
        out.append(m.shader_name)
        out.append("{")
        out.append("\tnopicmip")
        if m.kind == EMISSIVE:
            # a source, not a surface: it must not dim when the room does
            out += ["\t{", f"\t\tmap {img}", "\t\trgbGen identity", "\t}",
                    "\t{", f"\t\tmap {img}", "\t\tblendfunc GL_ONE GL_ONE",
                    f"\t\trgbGen wave sin {m.halo:.2f} {m.halo * 0.35:.2f} 0 0.13", "\t}"]
        else:
            out += ["\t{", f"\t\tmap {img}", "\t\trgbGen lightingDiffuse", "\t}"]
        out.append("}")
        out.append("")
    return "\n".join(out)


def build(materials: Sequence[Material], out_dir: Path, *, pak: Path = PAK,
          photoreal_root: Path = PHOTOREAL) -> dict:
    """Stage images + shader script into a pk3 source directory."""
    out_dir = Path(out_dir)
    resolved = [resolve(m, pak=pak, photoreal_root=photoreal_root) for m in materials]
    for m in resolved:
        dst = out_dir / "textures" / f"{m.name}{m.resolved['ext']}"
        dst.parent.mkdir(parents=True, exist_ok=True)
        if m.resolved["origin"] == "PHOTOREAL_UPSCALE_4X":
            dst.write_bytes(Path(m.resolved["path"]).read_bytes())
        else:
            src, ext = m.source, m.resolved["ext"]
            with zipfile.ZipFile(pak) as z:
                dst.write_bytes(z.read(src + ext))
    shader = out_dir / "scripts" / "pantheon_materials.shader"
    shader.parent.mkdir(parents=True, exist_ok=True)
    shader.write_text(shader_text(resolved), encoding="utf-8")

    manifest = {"materials": [{"name": m.shader_name, "source": m.source,
                               "kind": m.kind, **m.resolved} for m in resolved],
                "photoreal_used": sum(1 for m in resolved
                                      if m.resolved["origin"] == "PHOTOREAL_UPSCALE_4X"),
                "count": len(resolved)}
    (out_dir / "pantheon_materials.json").write_text(json.dumps(manifest, indent=1),
                                                     encoding="utf-8")
    return manifest
