"""clutch_recorder.csv is regenerated by the definition proven against v1:
round wins joined to the demo hash, deduped across duplicate demo files, and
filtered to the recorder by alias name."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "engine" / "parser"))

from engine.parser import clutch_products as CP


def _win(demo, rnd, start, player, client=3):
    return {"demo": demo, "round": rnd, "clutch_start_ms": start, "clutch_end_ms": start + 5000,
            "player_name": player, "player_client": client, "enemies_alive_at_start": 2,
            "kills_during_clutch": 2, "weapons": "ROCKET", "outcome": "WIN",
            "rank_score": 10.0, "map": "m", "duration_ms": 5000}


def test_join_dedupe_and_alias_filter():
    wins = [
        _win("a.dm_73", 1, 1000, "^1Tr4sH"),
        _win("a_copy.dm_73", 1, 1000, "^1Tr4sH"),   # duplicate file, same content
        _win("b.dm_73", 2, 5000, "Someone"),
        _win("unknown.dm_73", 1, 1000, "Tr4sH"),     # not in the catalogue
    ]
    name_to_hash = {"a.dm_73": "H1", "a_copy.dm_73": "H1", "b.dm_73": "H2"}
    all_players, recorder = CP.derive(wins, name_to_hash)
    assert [(r["canonical_demo_hash"], r["round"]) for r in all_players] == [("H1", 1), ("H2", 2)]
    assert [r["canonical_demo_hash"] for r in recorder] == ["H1"]


def test_the_written_columns_match_what_the_readers_join_on():
    assert CP.JOINED_COLS[:2] == ["demo", "canonical_demo_hash"]
    for col in ("clutch_start_ms", "clutch_end_ms", "enemies_alive_at_start", "outcome"):
        assert col in CP.JOINED_COLS
