"""Generated from msg.c by engine/parser/gen_netfields.py.

DO NOT EDIT. Regenerate instead. A test asserts this file still
matches the engine source, so hand-editing it will fail loudly.
"""

# playerStateFieldsQ3 -- used by protocol(s): Q3, 73 -- 48 fields
PLAYERSTATE_Q3 = [
    (  0, 'commandTime'           , '32', False),
    (  1, 'origin[0]'             , '0', False),
    (  2, 'origin[1]'             , '0', False),
    (  3, 'bobCycle'              , '8', False),
    (  4, 'velocity[0]'           , '0', False),
    (  5, 'velocity[1]'           , '0', False),
    (  6, 'viewangles[1]'         , '0', False),
    (  7, 'viewangles[0]'         , '0', False),
    (  8, 'weaponTime'            , '-16', True),
    (  9, 'origin[2]'             , '0', False),
    ( 10, 'velocity[2]'           , '0', False),
    ( 11, 'legsTimer'             , '8', False),
    ( 12, 'pm_time'               , '-16', True),
    ( 13, 'eventSequence'         , '16', False),
    ( 14, 'torsoAnim'             , '8', False),
    ( 15, 'movementDir'           , '4', False),
    ( 16, 'events[0]'             , '8', False),
    ( 17, 'legsAnim'              , '8', False),
    ( 18, 'events[1]'             , '8', False),
    ( 19, 'pm_flags'              , '16', False),
    ( 20, 'groundEntityNum'       , 'GENTITYNUM_BITS', False),
    ( 21, 'weaponstate'           , '4', False),
    ( 22, 'eFlags'                , '16', False),
    ( 23, 'externalEvent'         , '10', False),
    ( 24, 'gravity'               , '16', False),
    ( 25, 'speed'                 , '16', False),
    ( 26, 'delta_angles[1]'       , '16', False),
    ( 27, 'externalEventParm'     , '8', False),
    ( 28, 'viewheight'            , '-8', True),
    ( 29, 'damageEvent'           , '8', False),
    ( 30, 'damageYaw'             , '8', False),
    ( 31, 'damagePitch'           , '8', False),
    ( 32, 'damageCount'           , '8', False),
    ( 33, 'generic1'              , '8', False),
    ( 34, 'pm_type'               , '8', False),
    ( 35, 'delta_angles[0]'       , '16', False),
    ( 36, 'delta_angles[2]'       , '16', False),
    ( 37, 'torsoTimer'            , '12', False),
    ( 38, 'eventParms[0]'         , '8', False),
    ( 39, 'eventParms[1]'         , '8', False),
    ( 40, 'clientNum'             , '8', False),
    ( 41, 'weapon'                , '5', False),
    ( 42, 'viewangles[2]'         , '0', False),
    ( 43, 'grapplePoint[0]'       , '0', False),
    ( 44, 'grapplePoint[1]'       , '0', False),
    ( 45, 'grapplePoint[2]'       , '0', False),
    ( 46, 'jumppad_ent'           , '10', False),
    ( 47, 'loopSound'             , '16', False),
]

PLAYERSTATE_Q3_INDEX = {name: idx for idx, name, _b, _s in PLAYERSTATE_Q3}
PLAYERSTATE_Q3_SIGNED = {name for _i, name, _b, sgn in PLAYERSTATE_Q3 if sgn}

# playerStateFieldsQldm90 -- used by protocol(s): 90 -- 50 fields
PLAYERSTATE_QLDM90 = [
    (  0, 'commandTime'           , '32', False),
    (  1, 'origin[0]'             , '0', False),
    (  2, 'origin[1]'             , '0', False),
    (  3, 'bobCycle'              , '8', False),
    (  4, 'velocity[0]'           , '0', False),
    (  5, 'velocity[1]'           , '0', False),
    (  6, 'viewangles[1]'         , '0', False),
    (  7, 'viewangles[0]'         , '0', False),
    (  8, 'weaponTime'            , '-16', True),
    (  9, 'origin[2]'             , '0', False),
    ( 10, 'velocity[2]'           , '0', False),
    ( 11, 'legsTimer'             , '8', False),
    ( 12, 'pm_time'               , '-16', True),
    ( 13, 'eventSequence'         , '16', False),
    ( 14, 'torsoAnim'             , '8', False),
    ( 15, 'movementDir'           , '4', False),
    ( 16, 'events[0]'             , '8', False),
    ( 17, 'legsAnim'              , '8', False),
    ( 18, 'events[1]'             , '8', False),
    ( 19, 'pm_flags'              , '24', False),
    ( 20, 'groundEntityNum'       , 'GENTITYNUM_BITS', False),
    ( 21, 'weaponstate'           , '4', False),
    ( 22, 'eFlags'                , '16', False),
    ( 23, 'externalEvent'         , '10', False),
    ( 24, 'gravity'               , '16', False),
    ( 25, 'speed'                 , '16', False),
    ( 26, 'delta_angles[1]'       , '16', False),
    ( 27, 'externalEventParm'     , '8', False),
    ( 28, 'viewheight'            , '-8', True),
    ( 29, 'damageEvent'           , '8', False),
    ( 30, 'damageYaw'             , '8', False),
    ( 31, 'damagePitch'           , '8', False),
    ( 32, 'damageCount'           , '8', False),
    ( 33, 'generic1'              , '8', False),
    ( 34, 'pm_type'               , '8', False),
    ( 35, 'delta_angles[0]'       , '16', False),
    ( 36, 'delta_angles[2]'       , '16', False),
    ( 37, 'torsoTimer'            , '12', False),
    ( 38, 'eventParms[0]'         , '8', False),
    ( 39, 'eventParms[1]'         , '8', False),
    ( 40, 'clientNum'             , '8', False),
    ( 41, 'weapon'                , '5', False),
    ( 42, 'viewangles[2]'         , '0', False),
    ( 43, 'grapplePoint[0]'       , '0', False),
    ( 44, 'grapplePoint[1]'       , '0', False),
    ( 45, 'grapplePoint[2]'       , '0', False),
    ( 46, 'jumppad_ent'           , '10', False),
    ( 47, 'loopSound'             , '16', False),
    ( 48, 'jumpTime'              , '32', False),
    ( 49, 'doubleJumped'          , '1', False),
]

PLAYERSTATE_QLDM90_INDEX = {name: idx for idx, name, _b, _s in PLAYERSTATE_QLDM90}
PLAYERSTATE_QLDM90_SIGNED = {name for _i, name, _b, sgn in PLAYERSTATE_QLDM90 if sgn}

# playerStateFieldsQldm91 -- used by protocol(s): 91 -- 58 fields
PLAYERSTATE_QLDM91 = [
    (  0, 'commandTime'           , '32', False),
    (  1, 'origin[0]'             , '0', False),
    (  2, 'origin[1]'             , '0', False),
    (  3, 'bobCycle'              , '8', False),
    (  4, 'velocity[0]'           , '0', False),
    (  5, 'velocity[1]'           , '0', False),
    (  6, 'viewangles[1]'         , '0', False),
    (  7, 'viewangles[0]'         , '0', False),
    (  8, 'weaponTime'            , '-16', True),
    (  9, 'origin[2]'             , '0', False),
    ( 10, 'velocity[2]'           , '0', False),
    ( 11, 'legsTimer'             , '8', False),
    ( 12, 'pm_time'               , '-16', True),
    ( 13, 'eventSequence'         , '16', False),
    ( 14, 'torsoAnim'             , '8', False),
    ( 15, 'movementDir'           , '4', False),
    ( 16, 'events[0]'             , '8', False),
    ( 17, 'legsAnim'              , '8', False),
    ( 18, 'events[1]'             , '8', False),
    ( 19, 'pm_flags'              , '24', False),
    ( 20, 'groundEntityNum'       , 'GENTITYNUM_BITS', False),
    ( 21, 'weaponstate'           , '4', False),
    ( 22, 'eFlags'                , '16', False),
    ( 23, 'externalEvent'         , '10', False),
    ( 24, 'gravity'               , '16', False),
    ( 25, 'speed'                 , '16', False),
    ( 26, 'delta_angles[1]'       , '16', False),
    ( 27, 'externalEventParm'     , '8', False),
    ( 28, 'viewheight'            , '-8', True),
    ( 29, 'damageEvent'           , '8', False),
    ( 30, 'damageYaw'             , '8', False),
    ( 31, 'damagePitch'           , '8', False),
    ( 32, 'damageCount'           , '8', False),
    ( 33, 'generic1'              , '8', False),
    ( 34, 'pm_type'               , '8', False),
    ( 35, 'delta_angles[0]'       , '16', False),
    ( 36, 'delta_angles[2]'       , '16', False),
    ( 37, 'torsoTimer'            , '12', False),
    ( 38, 'eventParms[0]'         , '8', False),
    ( 39, 'eventParms[1]'         , '8', False),
    ( 40, 'clientNum'             , '8', False),
    ( 41, 'weapon'                , '5', False),
    ( 42, 'weaponPrimary'         , '8', False),
    ( 43, 'viewangles[2]'         , '0', False),
    ( 44, 'grapplePoint[0]'       , '0', False),
    ( 45, 'grapplePoint[1]'       , '0', False),
    ( 46, 'grapplePoint[2]'       , '0', False),
    ( 47, 'jumppad_ent'           , '10', False),
    ( 48, 'loopSound'             , '16', False),
    ( 49, 'jumpTime'              , '32', False),
    ( 50, 'doubleJumped'          , '1', False),
    ( 51, 'crouchTime'            , '32', False),
    ( 52, 'crouchSlideTime'       , '32', False),
    ( 53, 'location'              , '8', False),
    ( 54, 'fov'                   , '8', False),
    ( 55, 'forwardmove'           , '8', False),
    ( 56, 'rightmove'             , '8', False),
    ( 57, 'upmove'                , '8', False),
]

PLAYERSTATE_QLDM91_INDEX = {name: idx for idx, name, _b, _s in PLAYERSTATE_QLDM91}
PLAYERSTATE_QLDM91_SIGNED = {name for _i, name, _b, sgn in PLAYERSTATE_QLDM91 if sgn}

# entityStateFieldsQ3 -- used by protocol(s): Q3 -- 51 fields
ENTITYSTATE_Q3 = [
    (  0, 'pos.trTime'            , '32', False),
    (  1, 'pos.trBase[0]'         , '0', False),
    (  2, 'pos.trBase[1]'         , '0', False),
    (  3, 'pos.trDelta[0]'        , '0', False),
    (  4, 'pos.trDelta[1]'        , '0', False),
    (  5, 'pos.trBase[2]'         , '0', False),
    (  6, 'apos.trBase[1]'        , '0', False),
    (  7, 'pos.trDelta[2]'        , '0', False),
    (  8, 'apos.trBase[0]'        , '0', False),
    (  9, 'event'                 , '10', False),
    ( 10, 'angles2[1]'            , '0', False),
    ( 11, 'eType'                 , '8', False),
    ( 12, 'torsoAnim'             , '8', False),
    ( 13, 'eventParm'             , '8', False),
    ( 14, 'legsAnim'              , '8', False),
    ( 15, 'groundEntityNum'       , 'GENTITYNUM_BITS', False),
    ( 16, 'pos.trType'            , '8', False),
    ( 17, 'eFlags'                , '19', False),
    ( 18, 'otherEntityNum'        , 'GENTITYNUM_BITS', False),
    ( 19, 'weapon'                , '8', False),
    ( 20, 'clientNum'             , '8', False),
    ( 21, 'angles[1]'             , '0', False),
    ( 22, 'pos.trDuration'        , '32', False),
    ( 23, 'apos.trType'           , '8', False),
    ( 24, 'origin[0]'             , '0', False),
    ( 25, 'origin[1]'             , '0', False),
    ( 26, 'origin[2]'             , '0', False),
    ( 27, 'solid'                 , '24', False),
    ( 28, 'powerups'              , 'MAX_POWERUPS', False),
    ( 29, 'modelindex'            , '8', False),
    ( 30, 'otherEntityNum2'       , 'GENTITYNUM_BITS', False),
    ( 31, 'loopSound'             , '8', False),
    ( 32, 'generic1'              , '8', False),
    ( 33, 'origin2[2]'            , '0', False),
    ( 34, 'origin2[0]'            , '0', False),
    ( 35, 'origin2[1]'            , '0', False),
    ( 36, 'modelindex2'           , '8', False),
    ( 37, 'angles[0]'             , '0', False),
    ( 38, 'time'                  , '32', False),
    ( 39, 'apos.trTime'           , '32', False),
    ( 40, 'apos.trDuration'       , '32', False),
    ( 41, 'apos.trBase[2]'        , '0', False),
    ( 42, 'apos.trDelta[0]'       , '0', False),
    ( 43, 'apos.trDelta[1]'       , '0', False),
    ( 44, 'apos.trDelta[2]'       , '0', False),
    ( 45, 'time2'                 , '32', False),
    ( 46, 'angles[2]'             , '0', False),
    ( 47, 'angles2[0]'            , '0', False),
    ( 48, 'angles2[2]'            , '0', False),
    ( 49, 'constantLight'         , '32', False),
    ( 50, 'frame'                 , '16', False),
]

ENTITYSTATE_Q3_INDEX = {name: idx for idx, name, _b, _s in ENTITYSTATE_Q3}
ENTITYSTATE_Q3_SIGNED = {name for _i, name, _b, sgn in ENTITYSTATE_Q3 if sgn}

# entityStateFieldsQldm73 -- used by protocol(s): 73 -- 53 fields
ENTITYSTATE_QLDM73 = [
    (  0, 'pos.trTime'            , '32', False),
    (  1, 'pos.trBase[0]'         , '0', False),
    (  2, 'pos.trBase[1]'         , '0', False),
    (  3, 'pos.trDelta[0]'        , '0', False),
    (  4, 'pos.trDelta[1]'        , '0', False),
    (  5, 'pos.trBase[2]'         , '0', False),
    (  6, 'apos.trBase[1]'        , '0', False),
    (  7, 'pos.trDelta[2]'        , '0', False),
    (  8, 'apos.trBase[0]'        , '0', False),
    (  9, 'pos.gravity'           , '32', False),
    ( 10, 'event'                 , '10', False),
    ( 11, 'angles2[1]'            , '0', False),
    ( 12, 'eType'                 , '8', False),
    ( 13, 'torsoAnim'             , '8', False),
    ( 14, 'eventParm'             , '8', False),
    ( 15, 'legsAnim'              , '8', False),
    ( 16, 'groundEntityNum'       , 'GENTITYNUM_BITS', False),
    ( 17, 'pos.trType'            , '8', False),
    ( 18, 'eFlags'                , '19', False),
    ( 19, 'otherEntityNum'        , 'GENTITYNUM_BITS', False),
    ( 20, 'weapon'                , '8', False),
    ( 21, 'clientNum'             , '8', False),
    ( 22, 'angles[1]'             , '0', False),
    ( 23, 'pos.trDuration'        , '32', False),
    ( 24, 'apos.trType'           , '8', False),
    ( 25, 'origin[0]'             , '0', False),
    ( 26, 'origin[1]'             , '0', False),
    ( 27, 'origin[2]'             , '0', False),
    ( 28, 'solid'                 , '24', False),
    ( 29, 'powerups'              , 'MAX_POWERUPS', False),
    ( 30, 'modelindex'            , '8', False),
    ( 31, 'otherEntityNum2'       , 'GENTITYNUM_BITS', False),
    ( 32, 'loopSound'             , '8', False),
    ( 33, 'generic1'              , '8', False),
    ( 34, 'origin2[2]'            , '0', False),
    ( 35, 'origin2[0]'            , '0', False),
    ( 36, 'origin2[1]'            , '0', False),
    ( 37, 'modelindex2'           , '8', False),
    ( 38, 'angles[0]'             , '0', False),
    ( 39, 'time'                  , '32', False),
    ( 40, 'apos.trTime'           , '32', False),
    ( 41, 'apos.trDuration'       , '32', False),
    ( 42, 'apos.trBase[2]'        , '0', False),
    ( 43, 'apos.trDelta[0]'       , '0', False),
    ( 44, 'apos.trDelta[1]'       , '0', False),
    ( 45, 'apos.trDelta[2]'       , '0', False),
    ( 46, 'apos.gravity'          , '32', False),
    ( 47, 'time2'                 , '32', False),
    ( 48, 'angles[2]'             , '0', False),
    ( 49, 'angles2[0]'            , '0', False),
    ( 50, 'angles2[2]'            , '0', False),
    ( 51, 'constantLight'         , '32', False),
    ( 52, 'frame'                 , '16', False),
]

ENTITYSTATE_QLDM73_INDEX = {name: idx for idx, name, _b, _s in ENTITYSTATE_QLDM73}
ENTITYSTATE_QLDM73_SIGNED = {name for _i, name, _b, sgn in ENTITYSTATE_QLDM73 if sgn}

