"""Generated from msg.c by engine/parser/gen_netfields.py.

DO NOT EDIT. Regenerate instead. A test asserts this file still
matches the engine source, so hand-editing it will fail loudly.
"""

# playerStateFieldsQ3 -- used by protocol(s): Q3, 73 -- 48 fields
PLAYERSTATE_Q3 = [
    (  0, 'commandTime'           , '32'),
    (  1, 'origin[0]'             , '0'),
    (  2, 'origin[1]'             , '0'),
    (  3, 'bobCycle'              , '8'),
    (  4, 'velocity[0]'           , '0'),
    (  5, 'velocity[1]'           , '0'),
    (  6, 'viewangles[1]'         , '0'),
    (  7, 'viewangles[0]'         , '0'),
    (  8, 'weaponTime'            , '-16'),
    (  9, 'origin[2]'             , '0'),
    ( 10, 'velocity[2]'           , '0'),
    ( 11, 'legsTimer'             , '8'),
    ( 12, 'pm_time'               , '-16'),
    ( 13, 'eventSequence'         , '16'),
    ( 14, 'torsoAnim'             , '8'),
    ( 15, 'movementDir'           , '4'),
    ( 16, 'events[0]'             , '8'),
    ( 17, 'legsAnim'              , '8'),
    ( 18, 'events[1]'             , '8'),
    ( 19, 'pm_flags'              , '16'),
    ( 20, 'groundEntityNum'       , 'GENTITYNUM_BITS'),
    ( 21, 'weaponstate'           , '4'),
    ( 22, 'eFlags'                , '16'),
    ( 23, 'externalEvent'         , '10'),
    ( 24, 'gravity'               , '16'),
    ( 25, 'speed'                 , '16'),
    ( 26, 'delta_angles[1]'       , '16'),
    ( 27, 'externalEventParm'     , '8'),
    ( 28, 'viewheight'            , '-8'),
    ( 29, 'damageEvent'           , '8'),
    ( 30, 'damageYaw'             , '8'),
    ( 31, 'damagePitch'           , '8'),
    ( 32, 'damageCount'           , '8'),
    ( 33, 'generic1'              , '8'),
    ( 34, 'pm_type'               , '8'),
    ( 35, 'delta_angles[0]'       , '16'),
    ( 36, 'delta_angles[2]'       , '16'),
    ( 37, 'torsoTimer'            , '12'),
    ( 38, 'eventParms[0]'         , '8'),
    ( 39, 'eventParms[1]'         , '8'),
    ( 40, 'clientNum'             , '8'),
    ( 41, 'weapon'                , '5'),
    ( 42, 'viewangles[2]'         , '0'),
    ( 43, 'grapplePoint[0]'       , '0'),
    ( 44, 'grapplePoint[1]'       , '0'),
    ( 45, 'grapplePoint[2]'       , '0'),
    ( 46, 'jumppad_ent'           , '10'),
    ( 47, 'loopSound'             , '16'),
]

PLAYERSTATE_Q3_INDEX = {name: idx for idx, name, _bits in PLAYERSTATE_Q3}

# playerStateFieldsQldm90 -- used by protocol(s): 90 -- 50 fields
PLAYERSTATE_QLDM90 = [
    (  0, 'commandTime'           , '32'),
    (  1, 'origin[0]'             , '0'),
    (  2, 'origin[1]'             , '0'),
    (  3, 'bobCycle'              , '8'),
    (  4, 'velocity[0]'           , '0'),
    (  5, 'velocity[1]'           , '0'),
    (  6, 'viewangles[1]'         , '0'),
    (  7, 'viewangles[0]'         , '0'),
    (  8, 'weaponTime'            , '-16'),
    (  9, 'origin[2]'             , '0'),
    ( 10, 'velocity[2]'           , '0'),
    ( 11, 'legsTimer'             , '8'),
    ( 12, 'pm_time'               , '-16'),
    ( 13, 'eventSequence'         , '16'),
    ( 14, 'torsoAnim'             , '8'),
    ( 15, 'movementDir'           , '4'),
    ( 16, 'events[0]'             , '8'),
    ( 17, 'legsAnim'              , '8'),
    ( 18, 'events[1]'             , '8'),
    ( 19, 'pm_flags'              , '24'),
    ( 20, 'groundEntityNum'       , 'GENTITYNUM_BITS'),
    ( 21, 'weaponstate'           , '4'),
    ( 22, 'eFlags'                , '16'),
    ( 23, 'externalEvent'         , '10'),
    ( 24, 'gravity'               , '16'),
    ( 25, 'speed'                 , '16'),
    ( 26, 'delta_angles[1]'       , '16'),
    ( 27, 'externalEventParm'     , '8'),
    ( 28, 'viewheight'            , '-8'),
    ( 29, 'damageEvent'           , '8'),
    ( 30, 'damageYaw'             , '8'),
    ( 31, 'damagePitch'           , '8'),
    ( 32, 'damageCount'           , '8'),
    ( 33, 'generic1'              , '8'),
    ( 34, 'pm_type'               , '8'),
    ( 35, 'delta_angles[0]'       , '16'),
    ( 36, 'delta_angles[2]'       , '16'),
    ( 37, 'torsoTimer'            , '12'),
    ( 38, 'eventParms[0]'         , '8'),
    ( 39, 'eventParms[1]'         , '8'),
    ( 40, 'clientNum'             , '8'),
    ( 41, 'weapon'                , '5'),
    ( 42, 'viewangles[2]'         , '0'),
    ( 43, 'grapplePoint[0]'       , '0'),
    ( 44, 'grapplePoint[1]'       , '0'),
    ( 45, 'grapplePoint[2]'       , '0'),
    ( 46, 'jumppad_ent'           , '10'),
    ( 47, 'loopSound'             , '16'),
    ( 48, 'jumpTime'              , '32'),
    ( 49, 'doubleJumped'          , '1'),
]

PLAYERSTATE_QLDM90_INDEX = {name: idx for idx, name, _bits in PLAYERSTATE_QLDM90}

# playerStateFieldsQldm91 -- used by protocol(s): 91 -- 58 fields
PLAYERSTATE_QLDM91 = [
    (  0, 'commandTime'           , '32'),
    (  1, 'origin[0]'             , '0'),
    (  2, 'origin[1]'             , '0'),
    (  3, 'bobCycle'              , '8'),
    (  4, 'velocity[0]'           , '0'),
    (  5, 'velocity[1]'           , '0'),
    (  6, 'viewangles[1]'         , '0'),
    (  7, 'viewangles[0]'         , '0'),
    (  8, 'weaponTime'            , '-16'),
    (  9, 'origin[2]'             , '0'),
    ( 10, 'velocity[2]'           , '0'),
    ( 11, 'legsTimer'             , '8'),
    ( 12, 'pm_time'               , '-16'),
    ( 13, 'eventSequence'         , '16'),
    ( 14, 'torsoAnim'             , '8'),
    ( 15, 'movementDir'           , '4'),
    ( 16, 'events[0]'             , '8'),
    ( 17, 'legsAnim'              , '8'),
    ( 18, 'events[1]'             , '8'),
    ( 19, 'pm_flags'              , '24'),
    ( 20, 'groundEntityNum'       , 'GENTITYNUM_BITS'),
    ( 21, 'weaponstate'           , '4'),
    ( 22, 'eFlags'                , '16'),
    ( 23, 'externalEvent'         , '10'),
    ( 24, 'gravity'               , '16'),
    ( 25, 'speed'                 , '16'),
    ( 26, 'delta_angles[1]'       , '16'),
    ( 27, 'externalEventParm'     , '8'),
    ( 28, 'viewheight'            , '-8'),
    ( 29, 'damageEvent'           , '8'),
    ( 30, 'damageYaw'             , '8'),
    ( 31, 'damagePitch'           , '8'),
    ( 32, 'damageCount'           , '8'),
    ( 33, 'generic1'              , '8'),
    ( 34, 'pm_type'               , '8'),
    ( 35, 'delta_angles[0]'       , '16'),
    ( 36, 'delta_angles[2]'       , '16'),
    ( 37, 'torsoTimer'            , '12'),
    ( 38, 'eventParms[0]'         , '8'),
    ( 39, 'eventParms[1]'         , '8'),
    ( 40, 'clientNum'             , '8'),
    ( 41, 'weapon'                , '5'),
    ( 42, 'weaponPrimary'         , '8'),
    ( 43, 'viewangles[2]'         , '0'),
    ( 44, 'grapplePoint[0]'       , '0'),
    ( 45, 'grapplePoint[1]'       , '0'),
    ( 46, 'grapplePoint[2]'       , '0'),
    ( 47, 'jumppad_ent'           , '10'),
    ( 48, 'loopSound'             , '16'),
    ( 49, 'jumpTime'              , '32'),
    ( 50, 'doubleJumped'          , '1'),
    ( 51, 'crouchTime'            , '32'),
    ( 52, 'crouchSlideTime'       , '32'),
    ( 53, 'location'              , '8'),
    ( 54, 'fov'                   , '8'),
    ( 55, 'forwardmove'           , '8'),
    ( 56, 'rightmove'             , '8'),
    ( 57, 'upmove'                , '8'),
]

PLAYERSTATE_QLDM91_INDEX = {name: idx for idx, name, _bits in PLAYERSTATE_QLDM91}

# entityStateFieldsQ3 -- used by protocol(s): Q3 -- 51 fields
ENTITYSTATE_Q3 = [
    (  0, 'pos.trTime'            , '32'),
    (  1, 'pos.trBase[0]'         , '0'),
    (  2, 'pos.trBase[1]'         , '0'),
    (  3, 'pos.trDelta[0]'        , '0'),
    (  4, 'pos.trDelta[1]'        , '0'),
    (  5, 'pos.trBase[2]'         , '0'),
    (  6, 'apos.trBase[1]'        , '0'),
    (  7, 'pos.trDelta[2]'        , '0'),
    (  8, 'apos.trBase[0]'        , '0'),
    (  9, 'event'                 , '10'),
    ( 10, 'angles2[1]'            , '0'),
    ( 11, 'eType'                 , '8'),
    ( 12, 'torsoAnim'             , '8'),
    ( 13, 'eventParm'             , '8'),
    ( 14, 'legsAnim'              , '8'),
    ( 15, 'groundEntityNum'       , 'GENTITYNUM_BITS'),
    ( 16, 'pos.trType'            , '8'),
    ( 17, 'eFlags'                , '19'),
    ( 18, 'otherEntityNum'        , 'GENTITYNUM_BITS'),
    ( 19, 'weapon'                , '8'),
    ( 20, 'clientNum'             , '8'),
    ( 21, 'angles[1]'             , '0'),
    ( 22, 'pos.trDuration'        , '32'),
    ( 23, 'apos.trType'           , '8'),
    ( 24, 'origin[0]'             , '0'),
    ( 25, 'origin[1]'             , '0'),
    ( 26, 'origin[2]'             , '0'),
    ( 27, 'solid'                 , '24'),
    ( 28, 'powerups'              , 'MAX_POWERUPS'),
    ( 29, 'modelindex'            , '8'),
    ( 30, 'otherEntityNum2'       , 'GENTITYNUM_BITS'),
    ( 31, 'loopSound'             , '8'),
    ( 32, 'generic1'              , '8'),
    ( 33, 'origin2[2]'            , '0'),
    ( 34, 'origin2[0]'            , '0'),
    ( 35, 'origin2[1]'            , '0'),
    ( 36, 'modelindex2'           , '8'),
    ( 37, 'angles[0]'             , '0'),
    ( 38, 'time'                  , '32'),
    ( 39, 'apos.trTime'           , '32'),
    ( 40, 'apos.trDuration'       , '32'),
    ( 41, 'apos.trBase[2]'        , '0'),
    ( 42, 'apos.trDelta[0]'       , '0'),
    ( 43, 'apos.trDelta[1]'       , '0'),
    ( 44, 'apos.trDelta[2]'       , '0'),
    ( 45, 'time2'                 , '32'),
    ( 46, 'angles[2]'             , '0'),
    ( 47, 'angles2[0]'            , '0'),
    ( 48, 'angles2[2]'            , '0'),
    ( 49, 'constantLight'         , '32'),
    ( 50, 'frame'                 , '16'),
]

ENTITYSTATE_Q3_INDEX = {name: idx for idx, name, _bits in ENTITYSTATE_Q3}

# entityStateFieldsQldm73 -- used by protocol(s): 73 -- 53 fields
ENTITYSTATE_QLDM73 = [
    (  0, 'pos.trTime'            , '32'),
    (  1, 'pos.trBase[0]'         , '0'),
    (  2, 'pos.trBase[1]'         , '0'),
    (  3, 'pos.trDelta[0]'        , '0'),
    (  4, 'pos.trDelta[1]'        , '0'),
    (  5, 'pos.trBase[2]'         , '0'),
    (  6, 'apos.trBase[1]'        , '0'),
    (  7, 'pos.trDelta[2]'        , '0'),
    (  8, 'apos.trBase[0]'        , '0'),
    (  9, 'pos.gravity'           , '32'),
    ( 10, 'event'                 , '10'),
    ( 11, 'angles2[1]'            , '0'),
    ( 12, 'eType'                 , '8'),
    ( 13, 'torsoAnim'             , '8'),
    ( 14, 'eventParm'             , '8'),
    ( 15, 'legsAnim'              , '8'),
    ( 16, 'groundEntityNum'       , 'GENTITYNUM_BITS'),
    ( 17, 'pos.trType'            , '8'),
    ( 18, 'eFlags'                , '19'),
    ( 19, 'otherEntityNum'        , 'GENTITYNUM_BITS'),
    ( 20, 'weapon'                , '8'),
    ( 21, 'clientNum'             , '8'),
    ( 22, 'angles[1]'             , '0'),
    ( 23, 'pos.trDuration'        , '32'),
    ( 24, 'apos.trType'           , '8'),
    ( 25, 'origin[0]'             , '0'),
    ( 26, 'origin[1]'             , '0'),
    ( 27, 'origin[2]'             , '0'),
    ( 28, 'solid'                 , '24'),
    ( 29, 'powerups'              , 'MAX_POWERUPS'),
    ( 30, 'modelindex'            , '8'),
    ( 31, 'otherEntityNum2'       , 'GENTITYNUM_BITS'),
    ( 32, 'loopSound'             , '8'),
    ( 33, 'generic1'              , '8'),
    ( 34, 'origin2[2]'            , '0'),
    ( 35, 'origin2[0]'            , '0'),
    ( 36, 'origin2[1]'            , '0'),
    ( 37, 'modelindex2'           , '8'),
    ( 38, 'angles[0]'             , '0'),
    ( 39, 'time'                  , '32'),
    ( 40, 'apos.trTime'           , '32'),
    ( 41, 'apos.trDuration'       , '32'),
    ( 42, 'apos.trBase[2]'        , '0'),
    ( 43, 'apos.trDelta[0]'       , '0'),
    ( 44, 'apos.trDelta[1]'       , '0'),
    ( 45, 'apos.trDelta[2]'       , '0'),
    ( 46, 'apos.gravity'          , '32'),
    ( 47, 'time2'                 , '32'),
    ( 48, 'angles[2]'             , '0'),
    ( 49, 'angles2[0]'            , '0'),
    ( 50, 'angles2[2]'            , '0'),
    ( 51, 'constantLight'         , '32'),
    ( 52, 'frame'                 , '16'),
]

ENTITYSTATE_QLDM73_INDEX = {name: idx for idx, name, _bits in ENTITYSTATE_QLDM73}

