# Make the review origin start at logon and stay up.
#
# The smallest mechanism that outlives every shell AND needs no admin rights.
#
# Register-ScheduledTask was tried first and is refused without elevation on
# this machine, so the supervisor is launched from the per-user Startup
# folder instead. Same guarantee for the case that actually bit us -- the
# origin surviving the death of whatever shell started it -- without asking
# the user for an admin prompt.
#
#   Install:   powershell -ExecutionPolicy Bypass -File scripts/install_review_task.ps1
#   Start now: powershell -ExecutionPolicy Bypass -File scripts/review_origin.ps1
#   Remove:    Remove-Item "$env:APPDATA/Microsoft/Windows/Start Menu/Programs/Startup/quake-legacy-review.cmd"
#   Log:       G:/QUAKE_LEGACY/output/review_origin.log
#
# If the machine is ever administered, scripts/review_origin.ps1 can be
# registered as a proper Scheduled Task or service instead; nothing else
# changes. Cloudflare Access and the tunnel are untouched either way.

$ErrorActionPreference = 'Stop'

$Script  = Join-Path 'G:\QUAKE_LEGACY\scripts' 'review_origin.ps1'
$Startup = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$Shim    = Join-Path $Startup 'quake-legacy-review.cmd'

if (-not (Test-Path $Script)) { throw "missing supervisor script: $Script" }
New-Item -ItemType Directory -Force -Path $Startup | Out-Null

$body = @"
@echo off
rem Starts the supervised review origin (127.0.0.1:8766) at logon.
rem Generated by scripts/install_review_task.ps1 -- edit that, not this.
start "" /b powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$Script"
"@
Set-Content -Path $Shim -Value $body -Encoding ascii

Write-Host "installed $Shim"
