"""creative_suite/engine/manifest_generator.py

Convert a studio_nle.db clip arrangement into the render pipeline's
text manifest files:

  creative_suite/engine/clip_lists/partNN.txt
  creative_suite/engine/clip_lists/partNN_overrides.txt

The render pipeline (render_part_v6.py) reads these files. This module
is the bridge between the UI's DB state and the pipeline.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

_CLIP_LISTS = Path(__file__).parent / "clip_lists"


def _basename(clip_path: str) -> str:
    return os.path.basename(clip_path)


def _fx_to_overrides(effects: list[dict[str, Any]]) -> dict[str, str]:
    """Map enabled FX stack entries to override key=value pairs."""
    out: dict[str, str] = {}
    for fx in effects:
        if not fx.get("enabled", 1):
            continue
        try:
            params = json.loads(fx.get("params") or "{}")
        except Exception:
            params = {}

        etype = fx.get("effect_type", "")
        if etype == "slowmo":
            out["slow"] = str(round(params.get("rate", 0.5), 2))
        elif etype == "speedup":
            out["slow"] = str(round(params.get("rate", 2.0), 2))
        # vignette/zoom/shine_on_kill/bass_drop/reverb_tail: render pipeline
        # extension hooks — annotated in overrides as flag= tags for future use
        elif etype in ("vignette", "zoom", "shine_on_kill", "bass_drop", "reverb_tail"):
            out.setdefault("flag", etype.upper())
    return out


def generate(part: int, clips: list[dict[str, Any]], output_dir: Path | None = None) -> tuple[Path, Path]:
    """Write partNN.txt and partNN_overrides.txt from a clip arrangement list.

    `clips` is the list returned by nle_db.get_arrangement() — each entry has:
      clip_path, role, is_fl, pair_path, effects[]

    Returns (clip_list_path, overrides_path).
    """
    out_dir = output_dir or _CLIP_LISTS
    out_dir.mkdir(parents=True, exist_ok=True)

    nn = f"{part:02d}"
    cl_path = out_dir / f"part{nn}.txt"
    ov_path = out_dir / f"part{nn}_overrides.txt"

    cl_lines: list[str] = [
        f"# Part {part} clip list — generated by studio NLE (manifest_generator.py)",
        "# Edit studio_nle.db via the UI, then regenerate. Manual edits will be overwritten.",
        "",
    ]
    ov_lines: list[str] = [
        f"# Part {part} — NLE-generated overrides",
        "# Grammar: <clip_filename>: key=value [, key=value ...]",
        "",
    ]

    # Sort by position (already sorted from DB, but be explicit)
    sorted_clips = sorted(clips, key=lambda c: c.get("position", 0))

    # Track which FP clips have already been emitted as part of a paired line
    emitted: set[str] = set()

    for clip in sorted_clips:
        cp   = clip.get("clip_path", "")
        base = _basename(cp)
        role = clip.get("role", "body")
        is_fl = bool(clip.get("is_fl"))
        pair  = clip.get("pair_path")
        fx    = clip.get("effects") or []

        if base in emitted:
            continue

        # Build the clip line
        if is_fl:
            # Orphaned FL clip with no FP partner — emit as standalone
            line = base
        elif pair:
            pair_base = _basename(pair)
            emitted.add(pair_base)
            line = f"{base} > {pair_base}"
        else:
            line = base

        # Role annotation prefix
        if role == "intro":
            line = line + " [intro]"
        elif role == "outro":
            line = line + " [outro]"

        cl_lines.append(line)
        emitted.add(base)

        # Overrides for this clip
        ov = _fx_to_overrides(fx)
        if ov:
            kv = ", ".join(f"{k}={v}" for k, v in ov.items())
            ov_lines.append(f"{base}: {kv}")

    cl_path.write_text("\n".join(cl_lines) + "\n", encoding="utf-8")
    ov_path.write_text("\n".join(ov_lines) + "\n", encoding="utf-8")
    return cl_path, ov_path
