"""Extract original cgame presentation functions VERBATIM into an oracle TU.

The point of an oracle is that it is not my code. So these functions are not
retyped, summarised or "ported" -- they are lifted byte-for-byte out of the
engine source, and a test re-extracts and fails if the copy ever drifts from
it. The only thing the harness supplies is a minimal context for the engine
globals the functions reach for.

    python extract_oracle.py --write
    python extract_oracle.py --check
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

SRC_ROOT = Path("G:/QUAKE_LEGACY/engine/pantheon_renderer/wolfcamql-11.3-src/"
                "wolfcamql-src/code")
OUT = Path(__file__).with_name("oracle_generated.c")

# (file, function signature line prefix) -- extracted whole, brace to brace.
WANT = [
    ("cgame/cg_players.c", "static void CG_SwingAngles("),
    # Lifted for real, not stubbed. A no-op here would let the oracle "agree"
    # with a PANTHEON that also does nothing, and prove neither.
    ("cgame/cg_players.c", "static void CG_AddPainTwitch("),
    ("cgame/cg_players.c", "void CG_PlayerAngles("),
    # ANIMATION_PHASE. Every replay, freeze, retime and retarget rests on
    # these, and until now they were only checked against my own closed form.
    ("cgame/cg_players.c", "static void CG_SetLerpFrameAnimation ("),
    ("cgame/cg_players.c", "static void CG_SetAnimFrame ("),
    ("cgame/cg_players.c", "void CG_RunLerpFrame("),
    ("cgame/cg_players.c", "void CG_ClearLerpFrame ("),
]


class ExtractError(RuntimeError):
    pass


def extract(path: Path, sig: str) -> str:
    text = path.read_text(errors="replace")
    i = text.find("\n" + sig)
    if i < 0:
        raise ExtractError("%s: cannot find %r" % (path.name, sig))
    i += 1
    # walk braces from the opening one so nested blocks are handled
    j = text.index("{", i)
    depth, k = 0, j
    while k < len(text):
        if text[k] == "{":
            depth += 1
        elif text[k] == "}":
            depth -= 1
            if depth == 0:
                return text[i:k + 1]
        k += 1
    raise ExtractError("%s: unbalanced braces in %r" % (path.name, sig))


def build() -> tuple[str, list[tuple[str, str, str]]]:
    parts, manifest = [], []
    for rel, sig in WANT:
        p = SRC_ROOT / rel
        body = extract(p, sig)
        digest = hashlib.sha256(body.encode()).hexdigest()[:16]
        manifest.append((rel, sig.strip(), digest))
        parts.append("/* ---- %s :: %s  (sha256:%s) ---- */\n%s\n"
                     % (rel, sig.strip(), digest, body))
    head = [
        "/* GENERATED by extract_oracle.py -- DO NOT EDIT.",
        " *",
        " * These function bodies are lifted VERBATIM from the WolfcamQL 11.3",
        " * source so the oracle cannot quietly become a second copy of",
        " * PANTHEON's own logic. Regenerate rather than edit; a test fails if",
        " * this file and the engine source disagree.",
        " */",
        '#include "oracle_context.h"',
        "",
    ]
    return "\n".join(head) + "\n".join(parts), manifest


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    if not SRC_ROOT.exists():
        print("engine source not present: %s" % SRC_ROOT, file=sys.stderr)
        return 2
    text, manifest = build()

    if args.write:
        OUT.write_text(text, encoding="utf-8")
        print("wrote %s" % OUT)
        for rel, sig, dig in manifest:
            print("   %-24s %-34s sha256:%s" % (rel, sig, dig))
        return 0
    if args.check:
        if not OUT.exists():
            print("%s missing; run --write" % OUT, file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print("%s has DRIFTED from the engine source" % OUT, file=sys.stderr)
            return 1
        print("oracle matches the engine source")
        for rel, sig, dig in manifest:
            print("   %-24s %-34s sha256:%s" % (rel, sig, dig))
        return 0
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
