/* GENERATED by extract_oracle.py -- DO NOT EDIT.
 *
 * These function bodies are lifted VERBATIM from the WolfcamQL 11.3
 * source so the oracle cannot quietly become a second copy of
 * PANTHEON's own logic. Regenerate rather than edit; a test fails if
 * this file and the engine source disagree.
 */
#include "oracle_context.h"
/* ---- cgame/cg_players.c :: static void CG_SwingAngles(  (sha256:8886c348ef1e5450) ---- */
static void CG_SwingAngles( float destination, float swingTolerance, float clampTolerance,
					float speed, float *angle, qboolean *swinging ) {
	float	swing;
	float	move;
	float	scale;

	if ( !*swinging ) {
		// see if a swing should be started
		swing = AngleSubtract( *angle, destination );
		if ( swing > swingTolerance || swing < -swingTolerance ) {
			*swinging = qtrue;
		}
	}

	if ( !*swinging ) {
		return;
	}

	// modify the speed depending on the delta
	// so it doesn't seem so linear
	swing = AngleSubtract( destination, *angle );
	scale = fabs( swing );
	if ( scale < swingTolerance * 0.5 ) {
		scale = 0.5;
	} else if ( scale < swingTolerance ) {
		scale = 1.0;
	} else {
		scale = 2.0;
	}

	// swing towards the destination angle
	if ( swing >= 0 ) {
		move = cg.frametime * scale * speed;
		if ( move >= swing ) {
			move = swing;
			*swinging = qfalse;
		}
		*angle = AngleMod( *angle + move );
	} else if ( swing < 0 ) {
		move = cg.frametime * scale * -speed;
		if ( move <= swing ) {
			move = swing;
			*swinging = qfalse;
		}
		*angle = AngleMod( *angle + move );
	}

	// clamp to no more than tolerance
	swing = AngleSubtract( destination, *angle );
	if ( swing > clampTolerance ) {
		*angle = AngleMod( destination - (clampTolerance - 1) );
	} else if ( swing < -clampTolerance ) {
		*angle = AngleMod( destination + (clampTolerance - 1) );
	}
}

/* ---- cgame/cg_players.c :: static void CG_AddPainTwitch(  (sha256:93e26c21d6271c29) ---- */
static void CG_AddPainTwitch( const centity_t *cent, vec3_t torsoAngles ) {
	int		t;
	float	f;

	t = cg.time - cent->pe.painTime;
	if ( t >= PAIN_TWITCH_TIME ) {
		return;
	}

	f = 1.0 - (float)t / PAIN_TWITCH_TIME;

	if ( cent->pe.painDirection ) {
		torsoAngles[ROLL] += 20 * f;
	} else {
		torsoAngles[ROLL] -= 20 * f;
	}
}

/* ---- cgame/cg_players.c :: void CG_PlayerAngles(  (sha256:27381516f1439a48) ---- */
void CG_PlayerAngles( centity_t *cent, vec3_t legs[3], vec3_t torso[3], vec3_t head[3] ) {
	vec3_t		legsAngles, torsoAngles, headAngles;
	float		dest;
	static	int	movementOffsets[8] = { 0, 22, 45, -22, 0, 22, -45, -22 };
	vec3_t		velocity;
	float		speed;
	int			dir, clientNum;
	const clientInfo_t	*ci;


	VectorCopy( cent->lerpAngles, headAngles );
	headAngles[YAW] = AngleMod( headAngles[YAW] );
	VectorClear( legsAngles );
	VectorClear( torsoAngles );

	// --------- yaw -------------

	// allow yaw to drift a bit
	if ( ( cent->currentState.legsAnim & ~ANIM_TOGGLEBIT ) != LEGS_IDLE 
		 || (( cent->currentState.torsoAnim & ~ANIM_TOGGLEBIT ) != TORSO_STAND   &&  (cent->currentState.torsoAnim & ~ANIM_TOGGLEBIT) != TORSO_STAND2)) {
		// if not standing still, always point all in the same direction
		cent->pe.torso.yawing = qtrue;	// always center
		cent->pe.torso.pitching = qtrue;	// always center
		cent->pe.legs.yawing = qtrue;	// always center
	}

	//goto done;
	// adjust legs for movement dir
	if ( cent->currentState.eFlags & EF_DEAD ) {
		// don't let dead bodies twitch
		dir = 0;
	} else {
		dir = cent->currentState.angles2[YAW];
		if ( dir < 0 || dir > 7 ) {
			CG_Error( "Bad player movement angle" );
		}
	}
	legsAngles[YAW] = headAngles[YAW] + movementOffsets[ dir ];
	torsoAngles[YAW] = headAngles[YAW] + 0.25 * movementOffsets[ dir ];

	// torso
	CG_SwingAngles( torsoAngles[YAW], 25, 90, cg_swingSpeed.value, &cent->pe.torso.yawAngle, &cent->pe.torso.yawing );
	CG_SwingAngles( legsAngles[YAW], 40, 90, cg_swingSpeed.value, &cent->pe.legs.yawAngle, &cent->pe.legs.yawing );

	torsoAngles[YAW] = cent->pe.torso.yawAngle;
	legsAngles[YAW] = cent->pe.legs.yawAngle;

	//goto done;

	// --------- pitch -------------

	// only show a fraction of the pitch angle in the torso
	if ( headAngles[PITCH] > 180 ) {
		dest = (-360 + headAngles[PITCH]) * 0.75f;
	} else {
		dest = headAngles[PITCH] * 0.75f;
	}
	CG_SwingAngles( dest, 15, 30, 0.1f, &cent->pe.torso.pitchAngle, &cent->pe.torso.pitching );
	torsoAngles[PITCH] = cent->pe.torso.pitchAngle;

	//
	clientNum = cent->currentState.clientNum;
	if ( clientNum >= 0 && clientNum < MAX_CLIENTS ) {
		ci = &cgs.clientinfo[ clientNum ];
		if ( ci->fixedtorso ) {
			torsoAngles[PITCH] = 0.0f;
		}
	}

	// --------- roll -------------


	// lean towards the direction of travel
	VectorCopy( cent->currentState.pos.trDelta, velocity );
	if (CG_FreezeTagFrozen(cent->currentState.clientNum)) {
		//VectorSet(velocity, 0, 0, 0);
		//Com_Printf("%s frozen\n", cgs.clientinfo[cent->currentState.clientNum].name);
	}

	speed = VectorNormalize( velocity );
	speed *= cg_playerLeanScale.value;
	if (speed < 0) {
		speed = 0;
	}

	if ( speed > 0 ) {
		vec3_t	axis[3];
		float	side;

		speed *= 0.05f;

		AnglesToAxis( legsAngles, axis );
		side = speed * DotProduct( velocity, axis[1] );
		legsAngles[ROLL] -= side;

		side = speed * DotProduct( velocity, axis[0] );
		legsAngles[PITCH] += side;
	}

	//
	clientNum = cent->currentState.clientNum;
	if ( clientNum >= 0 && clientNum < MAX_CLIENTS ) {
		ci = &cgs.clientinfo[ clientNum ];
		if ( ci->fixedlegs ) {
			legsAngles[YAW] = torsoAngles[YAW];
			legsAngles[PITCH] = 0.0f;
			legsAngles[ROLL] = 0.0f;
		}
	}

	// pain twitch
	CG_AddPainTwitch( cent, torsoAngles );

	// done:
	// pull the angles back out of the hierarchial chain
	AnglesSubtract( headAngles, torsoAngles, headAngles );
	AnglesSubtract( torsoAngles, legsAngles, torsoAngles );
	AnglesToAxis( legsAngles, legs );
	AnglesToAxis( torsoAngles, torso );
	AnglesToAxis( headAngles, head );
}

/* ---- cgame/cg_players.c :: static void CG_SetLerpFrameAnimation (  (sha256:c7aa7b70cad83a30) ---- */
static void CG_SetLerpFrameAnimation (const clientInfo_t *ci, lerpFrame_t *lf, int newAnimation)
{
	const animation_t	*anim;

	lf->animationNumber = newAnimation;
	newAnimation &= ~ANIM_TOGGLEBIT;

	if ( newAnimation < 0 || newAnimation >= MAX_TOTALANIMATIONS ) {
		CG_Error( "Bad animation number: %i", newAnimation );
	}

	anim = &ci->animations[ newAnimation ];

	lf->animation = (animation_t *)anim;  //FIXME const
	lf->animationTime = lf->frameTime + anim->initialLerp;

	if ( cg_debugAnim.integer ) {
		CG_Printf( "Anim: %i\n", newAnimation );
	}
}

/* ---- cgame/cg_players.c :: static void CG_SetAnimFrame (  (sha256:61e8c20269a1d47b) ---- */
static void CG_SetAnimFrame (lerpFrame_t *lf, int time, float speedScale)
{
	const animation_t *anim;
	int f;
	int numFrames;

	anim = lf->animation;
	if (!anim->frameLerp) {
		return;
	}

	if ( time < lf->animationTime ) {
		//CG_Printf("initial lerp for %d  time %d < lf->animationTime %d\n", ci - cgs.clientinfo, time, lf->animationTime);
		lf->frameTime = lf->animationTime;		// initial lerp
	} else {
		lf->frameTime = lf->oldFrameTime + anim->frameLerp;
	}
	f = ( lf->frameTime - lf->animationTime ) / anim->frameLerp;
	f *= speedScale;		// adjust for haste, etc

	numFrames = anim->numFrames;
	if (anim->flipflop) {
		numFrames *= 2;
	}
	if ( f >= numFrames ) {
		f -= numFrames;
		if ( anim->loopFrames ) {
			f %= anim->loopFrames;
			f += anim->numFrames - anim->loopFrames;
		} else {
			f = numFrames - 1;
			// the animation is stuck at the end, so it
			// can immediately transition to another sequence
			lf->frameTime = time;
		}
	}
	if ( anim->reversed ) {
		lf->frame = anim->firstFrame + anim->numFrames - 1 - f;
	}
	else if (anim->flipflop && f>=anim->numFrames) {
		lf->frame = anim->firstFrame + anim->numFrames - 1 - (f%anim->numFrames);
	}
	else {
		lf->frame = anim->firstFrame + f;
	}
}

/* ---- cgame/cg_players.c :: void CG_RunLerpFrame(  (sha256:13003b6ad8f6c82a) ---- */
void CG_RunLerpFrame( const clientInfo_t *ci, lerpFrame_t *lf, int newAnimation, float speedScale, int time ) {
	//int			f;
	const animation_t	*anim;

	// debugging tool to get no animations
	if ( cg_animSpeed.integer == 0 ) {
		lf->oldFrame = lf->frame = lf->backlerp = 0;
		return;
	}

	// see if the animation sequence is switching
	if ( newAnimation != lf->animationNumber || !lf->animation ) {
		//Com_Printf("new anim for %d\n", ci - cgs.clientinfo);
		CG_SetLerpFrameAnimation( ci, lf, newAnimation );
	}

	// if we have passed the current frame, move it to
	// oldFrame and calculate a new frame
	if ( time >= lf->frameTime ) {
		lf->oldFrame = lf->frame;
		lf->oldFrameTime = lf->frameTime;

		// get the next frame based on the animation
		anim = lf->animation;
		if ( !anim->frameLerp ) {
			return;		// shouldn't happen
		}

		CG_SetAnimFrame(lf, time, speedScale);

#if 0
		if (cg.demoSeeking) {
			Com_Printf("%d  ent %d  frame %d  (lf->frameTime %d  lf->animationTime %d\n", cg.time, ci - cgs.clientinfo, lf->frame, lf->frameTime, lf->animationTime);
		}
#endif

		if ( time > lf->frameTime ) {
			lf->frameTime = time;
			if ( cg_debugAnim.integer ) {
				CG_Printf( "Clamp lf->frameTime\n");
			}
		}
	} else {
		//Com_Printf("lerp rewind\n");
	}

	if ( lf->frameTime > time + 200 ) {
		lf->frameTime = time;
	}

	if ( lf->oldFrameTime > time ) {
		lf->oldFrameTime = time;
	}
	// calculate current lerp value
	if ( lf->frameTime == lf->oldFrameTime ) {
		lf->backlerp = 0;
	} else {
		lf->backlerp = 1.0 - (float)( time - lf->oldFrameTime ) / ( lf->frameTime - lf->oldFrameTime );
	}
}

/* ---- cgame/cg_players.c :: void CG_ClearLerpFrame (  (sha256:c08b2f55a52a49c5) ---- */
void CG_ClearLerpFrame (const clientInfo_t *ci, lerpFrame_t *lf, int animationNumber , int time)
{
	//Com_Printf("clear lerp frame %d  %d\n", cg.time, time);

	lf->frameTime = lf->oldFrameTime = time;
	CG_SetLerpFrameAnimation( ci, lf, animationNumber );
	lf->oldFrame = lf->frame = lf->animation->firstFrame;
}
